M48
; DRILL file {KiCad 9.0.0} date 2025-11-28T03:58:57-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-28T03:58:57-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.048
%
G90
G05
T1
X98.95Y-100.771
X103.35Y-100.771
T2
X103.414Y-78.963
X137.526Y-78.963
X192.88Y-101.75
M30
